version: "3.1"
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: synonims_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/initialsetup.sql

  # server:
  #   build: ./server
  #   depends_on:
  #     - database
  #   links:
  #     - database
  #   environment:
  #     MYSQL_DATABASE: synonims_db
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: pass
  #   ports:
  #     - "4000:4000"
  #   restart: on-failure

  # angular:
  #   build: ./client/angular-client
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./client/angular-client:/app
