version: "3.3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: synonims_db
    ports:
      - "3306:3306"
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
